name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - run: cargo install cargo-llvm-cov
      - run: |
          cargo llvm-cov test --no-report
          cargo llvm-cov report --lcov --output-path target/report.lcov
          cargo llvm-cov report
      - uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: target/report.lcov

        
  coding-checks:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - run: |
          rustup component add rustfmt
          rustup component add clippy
      - run: |
          cargo fmt --check
          cargo clippy -- -Dwarnings
